<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="http://net.bhl.cdt.paxelerate.model/" nsPrefix="net.bhl.cdt.paxelerate">
  <eClassifiers xsi:type="ecore:EClass" name="Cabin" eSuperTypes="../../net.bhl.cdt.model/model/model.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xDimension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="2412"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yDimension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="364"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowNonexistent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aisleWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="64"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfDecks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aircraftType" lowerBound="1"
        eType="#//AircraftType" defaultValueLiteral="narrowbody"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simulationSettings" lowerBound="1"
        eType="#//SimulationProperties"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" lowerBound="1"
        upperBound="-1" eType="#//TravelClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doors" lowerBound="1" upperBound="-1"
        eType="#//Door" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lavatories" lowerBound="1"
        upperBound="-1" eType="#//Lavatory" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="galleys" lowerBound="1"
        upperBound="-1" eType="#//Galley" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stairways" upperBound="-1"
        eType="#//Stairway" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="curtains" upperBound="-1"
        eType="#//Curtain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stowages" upperBound="-1"
        eType="#//Stowage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passengers" upperBound="-1"
        eType="#//Passenger" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Row">
    <eStructuralFeatures xsi:type="ecore:EReference" name="seats" lowerBound="1" upperBound="-1"
        eType="#//Seat" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TravelClass">
    <eOperations name="tooManyPassengers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eOperations name="wrongRowStructure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" lowerBound="2" upperBound="-1"
        eType="#//Row" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequence" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="availableSeats" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seatPitch" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xDimensionOfSeats" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yDimensionOfSeats" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Placeholder String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rowStructure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="3-3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="loadFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="travelOption" lowerBound="1"
        eType="#//TravelOption" defaultValueLiteral="EconomyClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Seat" eSuperTypes="#//PhysicalObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seatBlocked" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="crewSeat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="letter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="travelClass" lowerBound="1"
        eType="#//TravelClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="row" lowerBound="1" eType="#//Row"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="occupied" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passenger" eType="#//Passenger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentlyFolded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Passenger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sex" eType="#//Sex"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="age" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="door" lowerBound="1" eType="#//Door"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seatID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="Mr. Placeholder"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boardingTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seat" lowerBound="1" eType="#//Seat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientationInDegree" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionX" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="positionY" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSeated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="walkingSpeed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="2.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startBoardingAfterDelay"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfWaits" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="luggageStowTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="luggageStowDistance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="travelClass" lowerBound="1"
        eType="#//TravelClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerMood" lowerBound="1"
        eType="#//PassengerMood"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfMakeWayOperations"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="luggage" eType="#//LuggageSize"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CrewMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="seat" eType="#//Seat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalObject" abstract="true">
    <eOperations name="outOfBounds" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="chain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments/>
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yDimension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xDimension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lavatory" eSuperTypes="#//PhysicalObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Galley" eSuperTypes="#//PhysicalObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Stairway" eSuperTypes="#//PhysicalObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//StairwayDirection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Curtain" eSuperTypes="#//PhysicalObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="postitionAfterRow" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="curtainOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stowage" eSuperTypes="#//PhysicalObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="Door">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onBothSides" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSimultaneousPassengers"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="waitingPassengers" upperBound="-1"
        eType="#//Passenger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="doorOption" lowerBound="1"
        eType="#//DoorOption" defaultValueLiteral="StandardDoor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Sex">
    <eLiterals name="male" value="1"/>
    <eLiterals name="female"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StairwayDirection">
    <eLiterals name="up" value="1"/>
    <eLiterals name="down" value="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AircraftType">
    <eLiterals name="regional"/>
    <eLiterals name="narrowbody" value="1" literal="narrowbody"/>
    <eLiterals name="widebody" value="2" literal="widebody"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PassengerMood">
    <eLiterals name="agressive"/>
    <eLiterals name="passive" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulationProperties">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="framesPerSecond" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usePresetSettings" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simulateWithoutUI" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfSimulationLoops"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="randomSortBetweenLoops"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="useFoldableSeats" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bringYourOwnSeat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" upperBound="-1"
        eType="#//SimulationResult"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sorting" eType="#//SortingStyle"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="simulationSpeedFactor"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seatInterferenceStandingUpPassengerWaitingTime"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="3"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="seatInterferenceProcessTime"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="7"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threadSleepTimeDefault"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="developerMode" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="luggageProperties" lowerBound="1"
        eType="#//LuggageProperties" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passengerProperties" lowerBound="1"
        eType="#//PassengerProperties" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengersBoardingPerMinute"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="18"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LuggageProperties">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="luggageStowDistanceFromSeatMean"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="80"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="luggageStowDistanceFromSeatDeviation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageOfPassengersWithNoLuggage"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageOfPassengersWithSmallLuggage"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageOfPassengersWithMediumLuggage"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageOfPassengersWithBigLuggage"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerSmallLuggageStowTimeMean"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="10"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerSmallLuggageStowTimeDeviation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerMediumLuggageStowTimeMean"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="15"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerMediumLuggageStowTimeDeviation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="7"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerBigLuggageStowTimeMean"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="20"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerBigLuggageStowTimeDeviation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimulationResult">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boardingTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengers" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boardingTimeString" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LuggageSize">
    <eLiterals name="small"/>
    <eLiterals name="medium" value="1"/>
    <eLiterals name="big" value="2"/>
    <eLiterals name="none" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SortingStyle">
    <eLiterals name="Random"/>
    <eLiterals name="WindowToAisle" value="1"/>
    <eLiterals name="RearToFront" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassengerProperties">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerWidthMeanMale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="47"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerWidthDeviationMale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="2.8"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerWeightMeanMale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="90"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerWeightDeviationMale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="20"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerHeightMeanMale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="177.5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerHeightDeviationMale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="11.1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerDepthMeanMale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="30"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerDepthDeviationMale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="percentageOfWomen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"
        defaultValueLiteral="50"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerWidthMeanFemale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="41.4"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerWidthDeviationFemale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="2.8"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerWeightMeanFemale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="60"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerWeightDeviationFemale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="15"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerHeightMeanFemale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="164.5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerHeightDeviationFemale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="11.5"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerDepthMeanFemale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="27"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passengerDepthDeviationFemale"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble" defaultValueLiteral="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TravelOption">
    <eLiterals name="FirstClass"/>
    <eLiterals name="BusinessClass" value="1"/>
    <eLiterals name="PremiumEconomyClass" value="2"/>
    <eLiterals name="EconomyClass" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ObjectOption">
    <eLiterals name="Seat"/>
    <eLiterals name="Galley" value="1"/>
    <eLiterals name="Lavatory" value="2"/>
    <eLiterals name="Stairway" value="3"/>
    <eLiterals name="Curtain" value="4"/>
    <eLiterals name="Stowage" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DoorOption">
    <eLiterals name="MainDoor"/>
    <eLiterals name="StandardDoor" value="1"/>
    <eLiterals name="EmergencyExit" value="2"/>
  </eClassifiers>
</ecore:EPackage>
